# docker-compose.yml
version: '3'
services:
  node1:
    image: alpine:latest
    command: sh -c "apk add --no-cache iproute2 iputils && tail -f /dev/null"
    networks:
      test_net:
        ipv4_address: 172.20.0.2
  
  node2:
    image: alpine:latest
    command: sh -c "apk add --no-cache iproute2 iputils && tail -f /dev/null"
    networks:
      test_net:
        ipv4_address: 172.20.0.3

networks:
  test_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
